// src/ImageAssets.js

export const ImageAssets = {
  restaurant: require('./Assets/restaurant.png'),
  cocktail: require('./Assets/cocktail.png'),
  dining: require('./Assets/dining.png'),
 cheif: require('./Assets/cheif.jpg'),
 dessert: require('./Assets/dessert.png'),
  steak: require('./Assets/steak.png'),
  coffee: require('./Assets/coffee.png'),  
  bestburgers: require('./Assets/bestburgers.png'),
  burger: require('./Assets/burger.png'),
  grillchicken: require('./Assets/grillchicken.png'),
  classicsbbq:require('./Assets/classicsbbq.png'),
  drinksbbq:require('./Assets/drinksbbq.png'),
  bg:require('./Assets/bg.jpg'),
  bacon:require('./Assets/bacon.png'),
  blackcoffee:require('./Assets/blackcoffee.png'),
  logo:require('./Assets/logo.png'),
pizza:require('./Assets/pizza.png'),
  cover:require('./Assets/cover.jpg'),
  r1:require('./Assets/r1.png'),
  r2:require('./Assets/r2.png'),
  r3:require('./Assets/r3.png'),
  Thomas:require('./Assets/Thomas.png'),
james:require('./Assets/james.png'),
  Minal:require('./Assets/Minal.png'),
  recentbg:require('./Assets/recentbg.jpg'),
  Delivery:require('./Assets/Delivery.png'),
order:require('./Assets/order.png'),
  cheezypizza:require('./Assets/cheezypizza.png'),
salad:require('./Assets/salad.png'),
img1:require('./Assets/img1.jpg'),
img2:require('./Assets/img2.jpg'),
followbg:require('./Assets/followbg.jpg'),
b1:require('./Assets/b1.png'),
b2:require('./Assets/b2.png'),
  cover2:require('./Assets/cover2.jpg'),
  carrot:require('./Assets/carrot.jpg'),
  sidedish:require('./Assets/sidedish.jpg'),
  organic:require('./Assets/organic.jpg'),
  good:require('./Assets/good.png'),
  garnish:require('./Assets/garnish.jpg'),
  cook:require('./Assets/cook.jpg'),
  garnishborder:require('./Assets/garnishborder.png'),
  c1:require('./Assets/c1.png'),
  c2:require('./Assets/c2.png'),
  c3:require('./Assets/c3.png'),
  c4:require('./Assets/c4.png'),
  c5:require('./Assets/c5.png'),
  c6:require('./Assets/c6.png'),
  tea:require('./Assets/tea.png'),
  shop:require('./Assets/shop.png'),
  juice:require('./Assets/juice.png'),
  donought:require('./Assets/donought.png'),
  d1:require('./Assets/d1.jpg'),
  e1:require('./Assets/e1.jpg'),
  e2:require('./Assets/e2.jpg'),  
  e3:require('./Assets/e3.jpg'),
  bg3:require('./Assets/bg3.png'),
  star5:require('./Assets/star5.png'),
  chickenburger:require('./Assets/chickenburger.png'),
  twoinone:require('./Assets/twoinone.png'),
  food1:require('./Assets/food1.jpg'),
  food2:require('./Assets/food2.jpg'),    
  food3:require('./Assets/food3.jpg'),
  food4:require('./Assets/food4.jpg'),
  bg4:require('./Assets/bg4.png'),
  work:require('./Assets/work.jpg'),
  bendi:require('./Assets/bendi.png'),
  n1:require('./Assets/n1.jpg'),
  n2:require('./Assets/n2.jpg'),
  junk:require('./Assets/junk.png'),
  burger4:require('./Assets/burger4.png'),
  i1:require('./Assets/i1.png'),
  i2:require('./Assets/i2.png'),
  i3:require('./Assets/i3.png'),
  i4:require('./Assets/i4.png'),
  o1:require('./Assets/o1.png'),
  o2:require('./Assets/o2.png'),
  bg5:require('./Assets/bg5.jpg'),
  m1:require('./Assets/m1.png'),
  blackbg:require('./Assets/blackbg.jpg'),
  left:require('./Assets/left.jpg'),
right:require('./Assets/right.jpg'),
grouppic:require('./Assets/grouppic.jpg'),
since:require('./Assets/since.jpg'),
sign:require('./Assets/sign.jpg'),
top1:require('./Assets/top1.jpg'),
ci1:require('./Assets/ci1.jpg'),
ci2:require('./Assets/ci2.png'),
ci3:require('./Assets/ci3.jpg'),
down:require('./Assets/down.png'),
coke:require('./Assets/coke.png'),
chicken:require('./Assets/chicken.png'),
pizzahouse:require('./Assets/pizzahouse.png'),
four:require('./Assets/four.png'),
s1:require('./Assets/s1.png'),
s2:require('./Assets/s2.png'),
cover4:require('./Assets/cover4.png'),
kfc:require('./Assets/kfc.png'),
dis:require('./Assets/dis.png'),
order1:require('./Assets/order1.png'),
order2:require('./Assets/order2.png'),
order3:require('./Assets/order3.png'),
sandwich:require('./Assets/sandwich.png'),
sat:require('./Assets/sat.png'),
ch1:require('./Assets/ch1.png'),
ch2:require('./Assets/ch2.png'),
ch3:require('./Assets/ch3.png'),
ch4:require('./Assets/ch4.png'),
bike:require('./Assets/bike.png'),
today:require('./Assets/today.png'),
background1:require('./Assets/background1.png'),
background2:require('./Assets/background2.png'),
background3:require('./Assets/background3.png'),
background4:require('./Assets/background4.png'),
off:require('./Assets/off.png'),
off2:require('./Assets/off2.png'),
cover6:require('./Assets/cover6.jpg'),
decor1:require('./Assets/decor1.png'),
decor2:require('./Assets/decor2.png'),
decor3:require('./Assets/decor3.png'),
decor4:require('./Assets/decor4.png'),
t1:require('./Assets/t1.png'),
t2:require('./Assets/t2.png'),
offer1:require('./Assets/offer1.png'),
offer2:require('./Assets/offer2.png'),
offer3:require('./Assets/offer3.png'),
offer4:require('./Assets/offer4.png'),
y1:require('./Assets/y1.png'),
y2:require('./Assets/y2.png'),
combo:require('./Assets/combo.png'),
family:require('./Assets/family.png'),
v1:require('./Assets/v1.png'),
v2:require('./Assets/v2.png'),
v8:require('./Assets/v8.png'),
v3:require('./Assets/v3.png'),
v4:require('./Assets/v4.png'),
v5:require('./Assets/v5.png'),
v6:require('./Assets/v6.png'),
v7:require('./Assets/v7.png'),
v7:require('./Assets/v7.png'),
freedel:require('./Assets/freedel.png'),
percentage:require('./Assets/percentage.png'),
sign:require('./Assets/sign.png'),
greybg:require('./Assets/greybg.png'),
yellowbg:require('./Assets/yellowbg.png'),
deliveryboy:require('./Assets/deliveryboy.png'),
pizzabg:require('./Assets/pizzabg.png'),
mushroombg:require('./Assets/mushroombg.png'),
client:require('./Assets/client.png'),
master:require('./Assets/master.jpg'),
starter:require('./Assets/starter.jpg'),
card1:require('./Assets/card1.jpg'),
card2:require('./Assets/card2.jpg'),
card3:require('./Assets/card3.jpg'),
f1:require('./Assets/f1.jpg'),
f2:require('./Assets/f2.jpg'),
f3:require('./Assets/f3.jpg'),
f4:require('./Assets/f4.jpg'),
f5:require('./Assets/f5.jpg'),
h1:require('./Assets/h1.jpg'),
h2:require('./Assets/h2.jpg'),
h3:require('./Assets/h3.jpg'),
h4:require('./Assets/h4.jpg'),
h5:require('./Assets/h5.jpg'),
tandoorichicken:require('./Assets/tandoorichicken.png'),
Shroom:require('./Assets/Shroom.png'),
subscribe:require('./Assets/subscribe.jpg'),





  
};
