// src/ImageAssets.js

export const ImageAssets = {
  restaurant: require('./Assets/restaurant.png'),
  cocktail: require('./Assets/cocktail.png'),
  dining: require('./Assets/dining.png'),
 cheif: require('./Assets/cheif.jpg'),
 dessert: require('./Assets/dessert.png'),
  steak: require('./Assets/steak.png'),
  coffee: require('./Assets/coffee.png'),
  burger: require('./Assets/burger.png'),
  grillchicken: require('./Assets/grillchicken.png'),
  classicsbbq:require('./Assets/classicsbbq.png'),
  drinksbbq:require('./Assets/drinksbbq.png'),
  bg:require('./Assets/bg.jpg'),
  bacon:require('./Assets/bacon.png'),
  blackcoffee:require('./Assets/blackcoffee.png'),
  logo:require('./Assets/logo.png'),
pizza:require('./Assets/pizza.png'),
  cover:require('./Assets/cover.jpg'),
  r1:require('./Assets/r1.png'),
  r2:require('./Assets/r2.png'),
  r3:require('./Assets/r3.png'),
  Thomas:require('./Assets/Thomas.png'),
james:require('./Assets/james.png'),
  Minal:require('./Assets/Minal.png'),
  recentbg:require('./Assets/recentbg.jpg'),
  Delivery:require('./Assets/Delivery.png'),
order:require('./Assets/order.png'),
  cheezypizza:require('./Assets/cheezypizza.png'),
salad:require('./Assets/salad.png'),
img1:require('./Assets/img1.jpg'),
img2:require('./Assets/img2.jpg'),
followbg:require('./Assets/followbg.jpg'),
b1:require('./Assets/b1.png'),
b2:require('./Assets/b2.png'),
  cover2:require('./Assets/cover2.jpg'),
  carrot:require('./Assets/carrot.jpg'),
  sidedish:require('./Assets/sidedish.jpg'),
  organic:require('./Assets/organic.jpg'),
  good:require('./Assets/good.png'),
  garnish:require('./Assets/garnish.jpg'),
  cook:require('./Assets/cook.jpg'),
  garnishborder:require('./Assets/garnishborder.png'),
  c1:require('./Assets/c1.png'),
  c2:require('./Assets/c2.png'),
  c3:require('./Assets/c3.png'),
  c4:require('./Assets/c4.png'),
  c5:require('./Assets/c5.png'),
  c6:require('./Assets/c6.png'),
  tea:require('./Assets/tea.png'),
  shop:require('./Assets/shop.png'),
  juice:require('./Assets/juice.png'),
  donought:require('./Assets/donought.png'),
  d1:require('./Assets/d1.jpg'),
  e1:require('./Assets/e1.jpg'),
  e2:require('./Assets/e2.jpg'),  
  e3:require('./Assets/e3.jpg'),
  bg3:require('./Assets/bg3.png'),
  star5:require('./Assets/star5.png'),
  chickenburger:require('./Assets/chickenburger.png'),
  twoinone:require('./Assets/twoinone.png'),
  food1:require('./Assets/food1.jpg'),
  food2:require('./Assets/food2.jpg'),    
  food3:require('./Assets/food3.jpg'),
  food4:require('./Assets/food4.jpg'),
  bg4:require('./Assets/bg4.png'),
  work:require('./Assets/work.jpg'),
  bendi:require('./Assets/bendi.png'),
  n1:require('./Assets/n1.jpg'),
  n2:require('./Assets/n2.jpg'),
  junk:require('./Assets/junk.png'),
  
};
