// src/ImageAssets.js

export const ImageAssets = {
  restaurant: require('./Assets/restaurant.png'),
  cocktail: require('./Assets/cocktail.png'),
  dining: require('./Assets/dining.png'),
 cheif: require('./Assets/cheif.jpg'),
 dessert: require('./Assets/dessert.png'),
  steak: require('./Assets/steak.png'),
  coffee: require('./Assets/coffee.png'),
  burger: require('./Assets/burger.png'),
  grillchicken: require('./Assets/grillchicken.png'),
  classicsbbq:require('./Assets/classicsbbq.png'),
  drinksbbq:require('./Assets/drinksbbq.png'),
  bg:require('./Assets/bg.jpg'),
  bacon:require('./Assets/bacon.png'),
  blackcoffee:require('./Assets/blackcoffee.png'),
  logo:require('./Assets/logo.png'),
pizza:require('./Assets/pizza.png'),
  cover:require('./Assets/cover.jpg'),
  r1:require('./Assets/r1.png'),
  r2:require('./Assets/r2.png'),
  r3:require('./Assets/r3.png'),
  Thomas:require('./Assets/Thomas.png'),
james:require('./Assets/james.png'),
  Minal:require('./Assets/Minal.png'),
  recentbg:require('./Assets/recentbg.jpg'),
  Delivery:require('./Assets/Delivery.png'),
order:require('./Assets/order.png'),
  cheezypizza:require('./Assets/cheezypizza.png'),
salad:require('./Assets/salad.png'),
img1:require('./Assets/img1.jpg'),
img2:require('./Assets/img2.jpg'),
followbg:require('./Assets/followbg.jpg'),
b1:require('./Assets/b1.png'),
b2:require('./Assets/b2.png'),
  cover2:require('./Assets/cover2.jpg'),

};
